#!/usr/bin/env python3
from sys import *
from math import *

def calc1(var, perc, a):
    res = perc - (a * sqrt(var))
    if (res * 100 < 0):
        return (0)
    if (res * 100 > 100):
        return (100)
    return (res)

def calc2(var, perc, a):
    res = perc + (a * sqrt(var))
    if (res * 100 < 0):
        return (0)
    if (res * 100 > 100):
        return (100)
    return (res)

def prints(pop, samp, perc, var):
    print("Population size:\t{}".format(pop))
    print("Sample size:\t\t{}".format(samp))
    print("Voting intentions:\t{:.2f}%".format(perc * 100))
    print("Variance:\t\t{:.6f}".format(var))
    print("95% confidence interval: [{:.2f}%; {:.2f}%]".format(calc1(var, perc, 1.96) * 100, calc2(var, perc, 1.96) * 100))
    print("99% confidence interval: [{:.2f}%; {:.2f}%]".format(calc1(var, perc, 2.58) * 100, calc2(var, perc, 2.58) * 100))

def main():
    try:
        if len(argv) != 4:
            exit(84)
        pop = int(argv[1])
        if pop <= 0:
            raise ValueError
        samp = int(argv[2])
        if samp <= 0:
            raise ValueError
        if samp > pop:
            raise ValueError
        perc = float(argv[3])
        if perc <= 0:
            raise ValueError
    except ValueError:
        print("Error: Invalid input")
        exit(84)

    perc /= 100
    if (pop == 1):
        exit(84)
    var = perc * (1 - perc) / samp * ((pop - samp) / (pop - 1))
    if (var < 0):
        exit(84)
    prints(pop, samp, perc, var)
    return 0


if __name__ == '__main__':
    main()